const { PrismaClient, DrillCategory } = require('@prisma/client');

const prisma = new PrismaClient();

async function main() {
  const drills = [
    {
      drillName: 'Passing Basics',
      duration: 10,
      numberOfSets: 1,
      numberOfReps: 1,
      restTime: 30,
      description: 'Practice short and long passes.',
      visualReference: null,
      drillCategory: DrillCategory.passing,
      materials: ['Cones', 'Soccer Ball'],
      createdByUser: false,
    },
    {
      drillName: 'Shooting Accuracy',
      duration: 15,
      numberOfSets: 1,
      numberOfReps: 1,
      restTime: 45,
      description: 'Improve shooting on goal with both feet.',
      visualReference: null,
      drillCategory: DrillCategory.shooting,
      materials: ['Goal', 'Soccer Ball'],
      createdByUser: false,
    },
    {
      drillName: 'Dribbling Cones',
      duration: 12,
      numberOfSets: 1,
      numberOfReps: 1,
      restTime: 30,
      description: 'Dribble through cones with control.',
      visualReference: null,
      drillCategory: DrillCategory.dribbling,
      materials: ['Cones', 'Soccer Ball'],
      createdByUser: false,
    },
    {
      drillName: 'Defensive Positioning',
      duration: 20,
      numberOfSets: 1,
      numberOfReps: 1,
      restTime: 60,
      description: 'Work on staying between attacker and goal.',
      visualReference: null,
      drillCategory: DrillCategory.defending,
      materials: ['None'],
      createdByUser: false,
    },
    {
      drillName: 'Fitness Sprint',
      duration: 8,
      numberOfSets: 1,
      numberOfReps: 1,
      restTime: 30,
      description: 'Short sprint intervals for fitness.',
      visualReference: null,
      drillCategory: DrillCategory.fitness,
      materials: ['Marker cones'],
      createdByUser: false,
    },
    {
      drillName: 'Tactical Awareness',
      duration: 25,
      numberOfSets: 1,
      numberOfReps: 1,
      restTime: 60,
      description: 'Study positioning and team tactics.',
      visualReference: null,
      drillCategory: DrillCategory.tactics,
      materials: ['Whiteboard'],
      createdByUser: false,
    },
    {
      drillName: 'Long Passing',
      duration: 15,
      numberOfSets: 1,
      numberOfReps: 1,
      restTime: 45,
      description: 'Practice long distance passing accuracy.',
      visualReference: null,
      drillCategory: DrillCategory.passing,
      materials: ['Cones', 'Soccer Ball'],
      createdByUser: false,
    },
    {
      drillName: 'Volley Shots',
      duration: 15,
      numberOfSets: 1,
      numberOfReps: 1,
      restTime: 45,
      description: 'Practice volleys from different angles.',
      visualReference: null,
      drillCategory: DrillCategory.shooting,
      materials: ['Goal', 'Soccer Ball'],
      createdByUser: false,
    },
    {
      drillName: 'Close Control Dribbling',
      duration: 10,
      numberOfSets: 1,
      numberOfReps: 1,
      restTime: 30,
      description: 'Keep ball close while dribbling at speed.',
      visualReference: null,
      drillCategory: DrillCategory.dribbling,
      materials: ['Soccer Ball'],
      createdByUser: false,
    },
    {
      drillName: 'Marking Drill',
      duration: 20,
      numberOfSets: 1,
      numberOfReps: 1,
      restTime: 60,
      description: 'Practice man-to-man marking.',
      visualReference: null,
      drillCategory: DrillCategory.defending,
      materials: ['None'],
      createdByUser: false,
    },
    {
      drillName: 'Endurance Run',
      duration: 30,
      numberOfSets: 1,
      numberOfReps: 1,
      restTime: 60,
      description: 'Long-distance running to build endurance.',
      visualReference: null,
      drillCategory: DrillCategory.fitness,
      materials: ['Running shoes'],
      createdByUser: false,
    },
    {
      drillName: 'Team Shape Drill',
      duration: 25,
      numberOfSets: 1,
      numberOfReps: 1,
      restTime: 60,
      description: 'Maintain team formation during attack and defense.',
      visualReference: null,
      drillCategory: DrillCategory.tactics,
      materials: ['Cones'],
      createdByUser: false,
    },
    {
      drillName: 'One-Touch Passing',
      duration: 12,
      numberOfSets: 1,
      numberOfReps: 1,
      restTime: 30,
      description: 'Quick one-touch passing under pressure.',
      visualReference: null,
      drillCategory: DrillCategory.passing,
      materials: ['Cones', 'Soccer Ball'],
      createdByUser: false,
    },
    {
      drillName: 'Power Shooting',
      duration: 15,
      numberOfSets: 1,
      numberOfReps: 1,
      restTime: 45,
      description: 'Shoot the ball with power and accuracy.',
      visualReference: null,
      drillCategory: DrillCategory.shooting,
      materials: ['Goal', 'Soccer Ball'],
      createdByUser: false,
    },
    {
      drillName: 'Shielding the Ball',
      duration: 10,
      numberOfSets: 1,
      numberOfReps: 1,
      restTime: 30,
      description: 'Protect the ball from defenders.',
      visualReference: null,
      drillCategory: DrillCategory.dribbling,
      materials: ['Soccer Ball'],
      createdByUser: false,
    },
  ];

  await prisma.drill.createMany({
    data: drills,
    skipDuplicates: true,
  });
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
